name: binder_env
channels:
  - defaults
dependencies:
  - backcall
  - ca-certificates
  - certifi
  - decorator
  - ipykernel
  - ipython
  - ipython_genutils
  - jedi
  - jupyter_client
  - jupyter_core
  - libedit
  - libffi
  - libsodium
  - ncurses
  - openssl
  - parso
  - pexpect
  - pickleshare
  - pip
  - prompt_toolkit
  - ptyprocess
  - pygments
  - python
  - python-dateutil
  - pyzmq
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - xz
  - zeromq
  - zlib
